### ISSUE TITLE
Launching the default hello world project raises a TypeLoadException

### ISSUE THREAD

**Issue by mayerwin** [ServiceStackApps/typescript-react-template#1]
I just added the TypeScript React App projects to my solution but launching the main project immediately raises:

> An exception of type 'System.TypeLoadException' occurred in ServiceStack.dll but was not handled in user code
> 
> Additional information: Method 'CreateInstance' in type 'ServiceStack.Host.ContainerResolveCache' from assembly 'ServiceStack, Version=4.5.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Not sure what to do from there. Based on the documentation the hello world example should work out of the box without having to implement anything.

**Comment by Layoric** [comment]
@mayerwin Yes, unfortunately this was due to how the ServiceStackVS plugin always tries to use the latest version and the latest release (v4.5.2) NuGet files not being in sync with other packages. I believe this will be fixed in the very near future but for now if you are creating new templates, update the solution wide NuGet packages by:
1. Right click on Solution
2. Select Manage NuGet Packages for Solution
3. Select Update tab
4. Select all
5. Update.

Once the package issues have been resolved, these steps won't be necessary and will work out-of-the-box.

**Comment by mayerwin** [comment]
Thanks it has indeed fixed the issue. Now it launches without error, but the page in Chrome is blank with the following source:

```
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">

    <!--build:css lib/css/lib.min.css-->
    <link rel="stylesheet" href="jspm_packages/npm/bootstrap.native@1.0.3/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" href="jspm_packages/npm/bootstrap.native@1.0.3/assets/css/theme.css" />
    <!--endbuild-->
    <!--build:css css/app.min.css-->
    <link rel="stylesheet" href="css/app.css" />
    <!-- endbuild -->
    <link rel="stylesheet" href="/platform.css" />

    <title>Dashboard</title>
</head>
<body>
    <div id="content"></div>
    <!-- build:js /system.js -->
    <script src="/jspm_packages/system.js"></script>
    <!-- endbuild -->
    <!-- build:js /config.js -->
    <script src="/config.js"></script>
    <!-- endbuild -->
    <!-- build:remove -->
    <script src="/deps.lib.js"></script>
    <!-- endbuild -->
    <!-- htmlbuild:appbundle -->
    <!-- endbuild -->

    <script>
        System.import("./src/app");
    </script>

    <script src="/platform.js"></script>

<!-- Visual Studio Browser Link -->
<script type="application/json" id="__browserLink_initializationData">
    {"appName":"Chrome"}
</script>
<script type="text/javascript" src="http://localhost:53811/31babdc23491449d9cbf00d4fb50036e/browserLink" async="async"></script>
<!-- End Browser Link -->

</body>
</html>
```

Is it normal? I was expecting to see: ![screenshot](https://raw.githubusercontent.com/ServiceStackApps/typescript-react-template/master/img/default-app.png)

**Comment by mythz** [comment]
Can you post any JavaScript errors you're seeing in Chrome WebInspector please?

**Comment by mayerwin** [comment]
Sure, here are the javascript errors: 

```
GET http://localhost:50758/jspm_packages/system.js 
(index):20 GET http://localhost:50758/jspm_packages/system.js 
config.js:1 Uncaught ReferenceError: System is not defined(anonymous function) @ config.js:1
(index):32 Uncaught ReferenceError: System is not defined(anonymous function) @ (index):32
tag_assistant_compiled.js:117 GET http://localhost:50758/jspm_packages/system.js 404 (Static File '/jspm_packages/system.js' not found)
```

**Comment by mythz** [comment]
ok that looks like the npm dependencies didn't install properly.

You can try running `npm install` from the Web App folder (i.e. where node_modules) to have it install missing npm dependencies otherwise you can try creating a new project again. 

It's working for me after creating a new ReactApp, updated all ServiceStack dependencies with NuGet then hitting F5.

**Comment by mythz** [comment]
I should also mention that you need to wait till npm has finished installing all the dependencies which can take a couple of minutes after the project template is created in VS.NET. You can view the progress by looking at **Bower/npm** in VS.NET's **Output** window, e.g:

![image](https://cloud.githubusercontent.com/assets/89361/19621726/18494784-9866-11e6-9bd9-1a21ad4c3d6c.png)

**Comment by mayerwin** [comment]
I just tried npm.install from within the folder `SolutionRoot/ProjectName/ProjectName/node_modules`, within `SolutionRoot/ProjectName/ProjectName`, and `SolutionRoot/ProjectName/ProjectName/jspm_packages`, none seemed to help. `ProjectName`refers to the name of the project chosen when adding the template.
I notice that there is no `system.js` file inside `SolutionRoot/ProjectName/ProjectName/ProjectName/jspm_packages`. Only a `github`and `npm`folder. I have the same behavior when installing in a completely new solution. I am using Visual Studio 2015 Update 3.

**Comment by mayerwin** [comment]
Also I had made sure to wait until npm had finished installing the dependencies when I added the project template (I had read this was important in the doc).

**Comment by mythz** [comment]
Ok can you try creating a new template from a shorter folder name e.g `c:\src\` or `c:\apps`, etc- then upgrading ServiceStack NuGet packages. You may be running into Windows file path limit.

I also have VS.NET 2015 Update 3 and was able to create a new ReactApp template which works after upgrading NuGet deps.

**Comment by mayerwin** [comment]
OK it works when installing in `c:\src\` (and when I tried to copy the resulting working solution to the previous location, it mentioned that the paths are too long, so it confirmed your diagnostic). Thanks Windows... But I need to have my file in another folder within Dropbox :/. So not a perfect solution. My current solution folder path is "only" 65 chars. Would there be a way to reduce the path length of these dependencies?

**Comment by mythz** [comment]
Ok great, glad to hear you got it working.

This is an inherent limit with npm on Windows which they're trying to resolve with npm v3 - there's some workarounds mention in this [NPM vs. Windows’ MAX_PATH Limitation](https://scottaddie.com/2015/08/16/npm-vs-windows-max_path-limitation/) blog post, but my general recommendation is to keep them in a short folder path.

**Comment by mythz** [comment]
@mayerwin FYI we just rolled out a v4.5.4 recovery release to fix this NuGet versioning issue so now all templates should work out of the gate without issue.

**Comment by mayerwin** [comment]
Great news. Thanks for the link on the workarounds. I just ran npm install -g npm@3.10.9 which should solve the issue (as version 3 has departed from the crazy folder nesting). However as I am trying to re-add the template, I am puzzled by the excruciating time taken to create the projects (sometimes it even seem to be in an infinite loop given the absence of progress, hanging on "Creating project '****'....", the number of files in the solution does not change, and there is no particularly high CPU usage nor bandwidth usage). It also took a long time and several attempts the previous times I loaded the template.
Is it because of nodejs? I am not used to this kind of bloatedness with ServiceStack, so it must come from somewhere else...

**Comment by Layoric** [comment]
@mayerwin if you are using VS 2015 or VS 2013 with the Bower/NPM extension, it waits until NPM has finished performing an `npm install` for the project client side dependencies. Check your output window and change it to show `Bower/npm` and you should see some messages about installing NPM dependencies.

Creating a new template also ensures you have the other Node development tools like Gulp, JSPM and Typings installed as well which can take a while depending on your connection.

All the TypeScript/Single page application templates do take a fair bit longer to get going and yes it's due to the NPM/Node side of things.

**Comment by mayerwin** [comment]
I wish things were more stable, but I just recreated a solution from the latest Template (tried both in c:\src\ and my documents, though the MAX_LENGTH issue should be resolved as I am using npm 3.10.9), and I keep getting the issue with `/jspm_packages/system.js` missing and preventing the site to load. I made sure Bower/npm was completed, and tried re-runnning `npm install` from the folder where `package.json`is present. To no avail.

The end of `npm install` stdout is:

```
ok   Installed npm:querystring@^0.2.0 (0.2.0)
ok   Installed github:jspm/nodelibs-os@^0.1.0 (0.1.0)

warn Error on lookup for npm:util
     Error: connect ETIMEDOUT 151.101.8.162:443
         at Object.exports._errnoException (util.js:907:11)
         at exports._exceptionWithHostPort (util.js:930:20)
         at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

err  Error looking up npm:util.

warn Installation changes not saved.
typings WARN deprecated 10/8/2016: "registry:dt/react#0.14.0+20160802191555" is deprecated (updated, replaced or removed)
typings WARN deprecated 8/31/2016: "registry:dt/isomorphic-fetch#0.0.0+20160524142046" is deprecated (updated, replaced or removed)

+-- servicestack-client@0.0.10
+-- es6-shim (global)
+-- isomorphic-fetch (global)
+-- react (global)
`-- react-dom (global)

npm WARN ReactDesktopApps1@0.0.1 No description
npm WARN ReactDesktopApps1@0.0.1 No repository field.
npm WARN ReactDesktopApps1@0.0.1 No license field.
```

As a side note, why use jspm at all? Is npm not enough (all the dependencies in jspm are from npm)?

**Comment by mayerwin** [comment]
I got it working, I had to run `npm install` many times as it was actually failing on some packages (time out) and stopped there instead of retrying. I wish there was a way to automatically check whether package.json has been properly installed.

**Comment by mythz** [comment]
JSPM is a universal module loader which takes care of loading your modules so you don't have to do manage them manually, it also includes bundling support which is able to reuse your dependency tree to bundle your App which we use when deploying to production - saving you from needing to configure other tools to do this.

Yeah I wish things were more stable as well, unfortunately the instability is due to npm's annoying preference for micro modules which requires a blank SPA project to install thousands of files which npm isn't that good at and has prompted Facebook to create their own yarn package manager which promises to be more stable.

We're always looking at reducing dependencies/tools required and we'd love to move to TypeScript's new `@types` annotations and just use yarn/npm but we haven't been able to get a good development experience atm, it's something we're keen to improve on though.

**Comment by mayerwin** [comment]
Thanks for the insight. For your information I was able to resolve the issue with `npm install` timing out after some time for some packages (and forcing to relaunch the command many times) by disabling my router's firewall and rebooting it.

Then a npm contributor mentioned in [this thread](https://github.com/npm/npm/issues/7200#issuecomment-258207258) that you can throttle the number of simultaneous connections with the following command (for example 3 maximum simultanous connections):

```
npm set maxsockets 3
```

The CLI has been allowing this option since npm@3.8.0. The default is 50 simultaneous connections max. See [this link](https://github.com/npm/npm/blob/5b4e3f3caff1f7ed30281b0b450de056a817bbc5/CHANGELOG.md#limit-concurrent-requests) for further reference.

**Comment by mayerwin** [comment]
So just for a final update, the above did not really resolve the issue (which was with `jspm`, not `npm`, and only occurred on my fibre connection, not 3G, so it has to do with the ISP somehow blocking requests after a while). 

However I was able to submit a [PR to jspm/npm](https://github.com/jspm/jspm-cli/issues/2154#issuecomment-258631073) which solves it for good. Basically, `jspm-npm` was not retrying upon encountering the error code even though it should have been.

**Comment by mythz** [comment]
oh that's awesome, going to appreciate the more stable usage, thx!
