### ISSUE TITLE
Issues with typings commands

### ISSUE THREAD

**Issue by mayerwin** [ServiceStackApps/typescript-react-template#2]
I am trying to install Type Definitions for redux and react-redux according to the documentation, running the following commands:

```
typings install redux --ambient --save
typings install react-redux --ambient --save
```

but the following error/warning occurs:

> typings install redux --ambient --save
> typings ERR! deprecated The "ambient" flag is deprecated. Please use "global" instead

See [this SO post](http://stackoverflow.com/questions/37808614/ambient-flag-is-deprecated) for some details.

Then trying with "global" as suggested also produces a lot of errors:

> typings install redux --global --save
> typings ERR! message Unable to find "redux" ("npm") in the registry.
> typings ERR! message However, we found "redux" for 1 other source: "dt"
> typings ERR! message You can install these using the "source" option.
> typings ERR! message We could use your help adding these typings to the registry: https://github.com/typings/registry
> typings ERR! caused by https://api.typings.org/entries/npm/redux/versions/latest responded with 404, expected it to equal 200
> 
> typings ERR! system Windows_NT 10.0.14393
> typings ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\Me\AppData\Roaming\npm\node_modules\typings\dist\bin.js" "install" "redux" "--global" "--save"
> typings ERR! node -v v4.6.1
> typings ERR! typings -v 1.4.0
> 
> typings ERR! If you need help, you may report this error at:
> typings ERR!   https://github.com/typings/typings/issues

Not sure if we can safely ignore this.

**Comment by mythz** [comment]
Unfortunately the latest version of typings changed their CLI instructions where they now want it to be:

```
typings install dt~redux --global
typings install dt~react-redux --global
```

We need to update our guidance, but we're waiting for [TypeScript future @types solution](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/) to be adopted which currently has issues with JSPM that needs resolving. Type definitions are the biggest short-coming in TypeScript we hope gets addressed soon by TypeScript and adopted by JS library authors.
