### ISSUE TITLE
Failed translating a Dto property of type "Tuple" in C# to TypeScript

### ISSUE THREAD

**Issue by mayerwin** [ServiceStackApps/typescript-react-template#4]
Using the "Update ServiceStack Reference" in Visual Studio, the following property: 

        `public List<Tuple<string, long, long>> MyTuples { get; set; }`

Is translated as:

    MyTuples: <string,,Int64,number>[];

Instead of:

    MyTuples: [string,number,number][];

**Comment by mayerwin** [comment]
I am also using properties of type `LocalDate`(from the excellent `NodaTime`), which are not translated. Is there any way to make it work without converting my property types to `DateTime`(which I don't like to store dates without time)?

**Comment by mythz** [comment]
C# Tuples is semantically different to TypeScript Tuples which is essentially an array of mixed types. The generated TypeScript DTOs need to match the wire format which for C# Tuples looks like `{"Item1":1,"Item2":"A"}` which is incompatible with what TypeScript tuples expect `[1,"A"]` so it's not possible to support as deserializing JSON wont be able to populate the TypeScript Tuple Type.

We'll look at generating C#-style Tuples in TypeScript but I'd recommend against their use in DTOs which are a problematic type that's treated differently across different Serializers and languages.

**Comment by mythz** [comment]
C# Tuples should now be supported in the latest [v4.5.5 release on MyGet](http://docs.servicestack.net/myget) although I'd still recommend against its use, named Types are cleaner and work everywhere..
